---
- name: Accept snmp_exporter connections.
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_port: "9116"
    jump: ACCEPT
    comment: Accept snmp_exporter connections.

- name: Accept blackbox_exporter connections.
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_port: "9115"
    jump: ACCEPT
    comment: Accept blackbox_exporter connections.

- name: Accept prometheus connections.
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_port: "9090"
    jump: ACCEPT
    comment: Accept prometheus connections.

- name: Accept alertmanager connections.
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_port: "9093"
    jump: ACCEPT
    comment: Accept alertmanager connections.

- name: Accept cAdvisor connections.
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_port: "8080"
    jump: ACCEPT
    comment: Accept cAdvisor connections.

- name: Accept grafana connections.
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_port: "{{ grafana_port | default('3000') }}"
    jump: ACCEPT
    comment: Accept grafana connections.

- name: Accept OpenSearch Dashboard connections.
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_port: "5601"
    jump: ACCEPT
    comment: Accept OpenSearch Dashboard connections.

- name: Accept OpenSearch REST API connections.
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_port: "9200"
    jump: ACCEPT
    comment: Accept OpenSearch REST API connections.

- name: Accept OpenSearch Cross-cluster search connections.
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_port: "9250"
    jump: ACCEPT
    comment: Accept OpenSearch Cross-cluster search connections.

- name: Accept OpenSearch Node communication and transport connections.
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_port: "9300"
    jump: ACCEPT
    comment: Accept OpenSearch Node communication and transport connections.

- name: Accept OpenSearchPerformance Analyzer connections.
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_port: "9600"
    jump: ACCEPT
    comment: Accept OpenSearch Performance Analyzer connections.

- name: Save iptables rules
  ansible.builtin.shell: iptables-save > /etc/sysconfig/iptables
  when: ansible_facts['distribution'] == "CentOS" or ansible_facts['distribution'] == "Amazon" or ansible_facts['distribution'] == "AlmaLinux"

- name: Save iptables rules
  ansible.builtin.shell: iptables-save > /etc/iptables/rules.v4
  when: ansible_facts['distribution'] == "Ubuntu"
