---
- name: Upgrade All Packages
  ansible.builtin.yum:
    name: "*"
    state: latest # noqa package-latest
    skip_broken: true

- name: Checking if reboot is needed
  ansible.builtin.shell: LAST_KERNEL=$(rpm -q --last kernel | awk 'NR==1{sub(/kernel-/,""); print $1}'); CURRENT_KERNEL=$(uname -r); if [ $LAST_KERNEL != $CURRENT_KERNEL ]; then echo 'reboot'; else echo 'no'; fi
  ignore_errors: true
  register: reboot_hint

- name: Rebooting
  ansible.builtin.reboot:
  ignore_errors: true
  when: reboot_hint.stdout.find("reboot") != -1

- name: Ensure EPEL Repo
  ansible.builtin.command: amazon-linux-extras install epel -y

- name: Update Yum Cache
  ansible.builtin.yum:
    name: "*"
    state: latest # noqa package-latest
    skip_broken: true
    update_cache: true

- name: Base packages
  ansible.builtin.yum:
    name: "{{ packages }}"
    state: latest # noqa package-latest
  vars:
    packages:
      - ansible
      - at
      - bash-completion
      - bash-completion-extras
      - bind-utils
      - bridge-utils
      - bzip2
      - chrony
      - cloud-utils
      - cloud-utils-growpart
      - deltarpm
      - genisoimage
      - git
      - hdparm
      - htop
      - ipmitool
      - iptables-services
      - jq
      - libselinux-python
      - mailx
      - net-tools
      - nfs-utils
      - postgresql
      - python3
      - python3-pip
      - rng-tools
      - tmux
      - vim
      - wget

- name: Enable rngd (Entropy) service
  ansible.builtin.systemd:
    name: rngd.service
    state: restarted
    enabled: true
